version: '2'

services:
    nginx: 
        restart: unless-stopped
        build:
            context: .
            dockerfile: ./docker/nginx/Dockerfile
        ports:
            - 80:80       
        volumes:
            - static_volume:/mash-app/server/django_static
            - ./docker/nginx/development:/etc/nginx/conf.d
        depends_on: 
            - server
    server:
        restart: unless-stopped
        build:
            context: .
            dockerfile: ./docker/server/Dockerfile
        volumes:
            
        entrypoint: /mash-app/docker/server/wsgi-entrypoint.sh
        volumes:
            - static_volume:/mash-app/server/django_static
        expose:
            - 8000        
            - 3000

volumes:
    static_volume: {}